<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>89eab577-052e-4536-8bc4-42aec457fb91</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Scoreboard where
		the Confidence is 0.90, 
		High risk is true;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
